GET http://localhost:3000/
###


### /USERS

GET http://localhost:3000/users/user_id
Authorization: Bearer jwt-token-valido
###

GET http://localhost:3000/users/6
Authorization: Bearer jwt-token-valido
###

POST http://localhost:3000/users
Authorization: Bearer jwt-token-valido
Content-Type: application/json

{
    "name": "alan turing",
    "username": "nikolatesla",
    "email": "nikol@tesla.com"
}
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "nikolatesla",
    "email": "nikol@tesla.com",
    "token": "xpto",
    "createdAt": "2026-07-30"
}
###


POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "nikolatesla",
    "email": "nikol@tesla.com",
    "createdAt": "2026-07-30"
}
###

POST http://localhost:3000/readings
Content-Type: application/json

{
    "bookId": "xpto-001",
    "pagesRead": "dez"
}

###
GET http://localhost:3000/books


###
POST http://localhost:3000/books
Content-Type: application/json
Authorization: Bearer jwt-token-valido

{
    "title": "teste",
    "author": "teste",
    "isbn": "teste",
    "pages": "teste"
}

###
POST http://localhost:3000/authors
Content-Type: application/json
Authorization: Bearer jwt-token-valido

{
    "name": "Jorge Amado"
}